name: deploy-mdb-atlas-app-service
run-name: ${{ github.actor }} deploys an app on the Atlas App Service
on: [workflow_dispatch]
jobs:
  build-astro-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
        working-directory: ./fe 
      - run: npm run build
        working-directory: ./fe
      - run: mkdir -p ./data/hosting/files
      - run: cp -R ./fe/dist/* ./data/hosting/files
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./data
  deploy-to-aas:
    runs-on: ubuntu-latest
    needs: build-astro-svelte
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g mongodb-realm-cli
      - run: mkdir -p build-artifact
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build-artifact
      - run: realm-cli login --api-key ${{ secrets.API_KEY }} --private-api-key ${{ secrets.PRIVATE_API_KEY }} -y
      - run: realm-cli pull --remote ${{ vars.APP_ID }}
      - run: cp -R ./build-artifact/* ./${{ vars.APP_NAME }}/hosting/files 
      - run: realm-cli push --remote ${{ vars.APP_ID }} -s -c -y
        working-directory: ./${{ vars.APP_NAME }}